services:
  postgres:
    image: postgres:latest
    container_name: database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_DOCKER}
    networks:
      - nestAPI
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    networks:
      - nestAPI
    ports:
      - ${PGADMIN_PORT}:80
    env_file:
      - .env

  nestjs-api:
    build:
      context: .
    container_name: api
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - nestAPI

networks:
  nestAPI:
    driver: bridge
    name: API
