services:
  postgres:
    image: postgres:latest
    networks:
      - postgres
    env_file:
      - .env
 
  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - postgres
    ports:
      - "8080:80"
    env_file:
      - .env
 
  nestjs-api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge